apiVersion: v1
kind: Secret
metadata:
  name: text2sql-frontend-secret
type: Opaque
data: {}
# Currently frontend doesn't have any specific secrets. 
# Added this file to fulfill the requirement of separated secret files for FE and BE.
